import cv2

# === YOLO SETTINGS ===
YOLO_INPUT_SIZE = 800
YOLO_INPUT_SHAPE = (YOLO_INPUT_SIZE, YOLO_INPUT_SIZE)
MODEL_ARCHITECTURE = "yolo11s-seg.pt"
MODEL_ARCHITECTURE_NAME = MODEL_ARCHITECTURE[:-3]
DATASET_YAML = "datasets/yolo_dataset/data.yaml"
MODEL_NAME = f"{MODEL_ARCHITECTURE_NAME}_frame_detector3"
TRAINING_EPOCHS = 200
TRAINING_BATCH_SIZE = 8

# === YOLO TEST SETTINGS ===
CONFIDENCE_THRESHOLD = 0.5
IOU_THRESHOLD = 0.65

# === CHARUCO BOARD SETTINGS ===
CHARUCOBOARD_ROWCOUNT = 5
CHARUCOBOARD_COLCOUNT = 5
SQUARE_LENGTH = 0.04  # 40 mm in meters
MARKER_LENGTH = 0.03  # 30 mm in meters
ARUCO_DICT_ID = cv2.aruco.DICT_6X6_250  # used locally
ARUCO_DICT = cv2.aruco.getPredefinedDictionary(ARUCO_DICT_ID)

# === REQUIREMENTS ===
MIN_MARKERS_PER_IMAGE = 6
MIN_CORNERS_PER_IMAGE = 6
MIN_VALID_IMAGES = 10
MEASUREMENT_ACCURACY_TARGET_MM = 10  # Target accuracy in millimeters

# === DETECTOR PARAMETER VALUES ===
ADAPTIVE_THRESH_WIN_SIZE_MIN = 3
ADAPTIVE_THRESH_WIN_SIZE_MAX = 23
ADAPTIVE_THRESH_WIN_SIZE_STEP = 10
MIN_MARKER_PERIMETER_RATE = 0.01
MAX_MARKER_PERIMETER_RATE = 2.0
CORNER_REFINEMENT_METHOD = cv2.aruco.CORNER_REFINE_SUBPIX

# === OUTPUT SETTINGS ===
TRAINING_OUTPUT_DIR = "yolo_training_output"
MEASUREMENT_OUTPUT_DIR = "measurement_results"
TEST_PREDICTIONS_OUTPUT_DIR = "test_predictions"
OUTPUT_JSON_FILE = "detection_results_segmentation_fixed.json"

# === DATASETS ===
LABELED_IMAGES_DIR = "datasets/testing_images/labeled"
UNLABELED_IMAGES_DIR = "datasets/testing_images/unlabeled"
NIGHT_TIME_IMAGES_DIR_PATH = "datasets/testing_images/night_time"
CONVERTED_FROM_OBB_TO_YOLO_DIR = "datasets/converted_from_obb_to_yolo/yolo_dataset"
BIG_WINDOWS_IMAGES_DIR_PATH = "datasets/testing_images/big_windows"
SUPER_TESTER_PATH = "datasets/testing_images/super_tester"
